### ISSUE TITLE
enb

### ISSUE THREAD

**Issue by voischev** [voischev/bem-social#54]

**Comment by zxqfox** [comment]
Проблемки?

/cc @blond

**Comment by blond** [comment]
эмм?

**Comment by zxqfox** [comment]
@blond Судя по отсутствию конфига для енб в библиотеке речь о переходе на enb сборку тестов и пр.

**Comment by zxqfox** [comment]
@blond @tadatuta Я понимаю, что немного поздновато, но может быть у нас есть руководство какое-то небольшое по миграции?

**Comment by tadatuta** [comment]
@zxqfox нет, но если бы было, то там было примерно так:
1. удалите все, что связано с `bem-tools`
2. напишите конфиг для ENB
преемственности в плане API нет от слова «совсем».

**Comment by zxqfox** [comment]
@tadatuta Начало крутое ;-)

А если с точки зрения кейсов? Типа:
- Вместо bem-pr используем enb-bem-docs, enb-bem-examples
- Для тестов enb-bem-specs

etc.

**Comment by verybigman** [comment]
bem-pr по любому нужен;)

**Comment by tadatuta** [comment]
К сожалению, пока самым простым вариантом остается
```sh
cp -r bem-components my-cool-library
cd my-cool-library
rm -rf *.blocks/*
```
и дальше осмысленный реплейс вхождения `bem-components` на `my-cool-library` и прочие сопутствующие правки.

Знаем, думаем над улучшением ситуации, скорбим вместе с вами.

**Comment by verybigman** [comment]
Я помогу;)

**Comment by zxqfox** [comment]
Выноси стоячих, чтоле? ;)

**Comment by voischev** [comment]
@verybigman фух.
